[build]
builder = "NIXPACKS"

[deploy]
startCommand = "pnpm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "indexer"

[services.env]
NODE_ENV = "production"
PONDER_LOG_LEVEL = "info"

